name: tales
description: A beautiful wallpaper app with clean architecture
publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  http: ^1.2.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1

  # Wallpaper-specific dependencies
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.0
  wallpaper_manager_plus: ^1.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_cache_manager: ^3.3.1
  image_gallery_saver: ^2.0.3

  # Dependency injection
  get_it: ^7.6.7

  # Network connectivity
  connectivity_plus: ^5.0.2

  # Environment variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
  intl: ^0.19.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/images/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/tales.png"


dependency_overrides:
  image_gallery_saver:
    path: ./local_plugins/image_gallery_saver

